### ISSUE TITLE
bug: agent-config-sync build fails on clean main — TS2367 in src/sync.test.ts (HeartbeatConfig vs boolean comparison)

### ISSUE THREAD

**Issue by NOVA-Openclaw** [NOVA-Openclaw/nova-mind#369]
During SE Run #333 production deploy (main @ 860a9e3), `agent-install.sh`'s agent-config-sync build failed identically on two independent clean installs (newhart, graybeard fresh clone):

```
src/sync.test.ts(1327,17): error TS2367: comparison between 'HeartbeatConfig | undefined' and 'boolean' have no overlap.
src/sync.test.ts(1458,17): error TS2367: comparison between 'HeartbeatConfig | undefined' and 'boolean' have no overlap.
src/sync.test.ts(1459,17): error TS2367: comparison between 'HeartbeatConfig | undefined' and 'boolean' have no overlap.
```

The test asserts `entry.heartbeat !== false` but the `heartbeat` field type is now `HeartbeatConfig | undefined` (changed in #273/#274, commits 795037b/8f99f3d). Pre-existing on main, NOT introduced by #359.

## Effect

`agent-config-sync` extension does not rebuild on install; deployed agents keep the previous build.

## Fix

Update the test assertions to match the `HeartbeatConfig` type (e.g. check for absence of the key / undefined rather than boolean `false`).

Discovered during: SE Run #333 production deploy.
