### PR TITLE
fix(agent_chat): declare openclaw dependency and install before build

### LINKED ISSUE #333: agent-install.sh: zod not installed into shared ~/.openclaw/node_modules — agent_chat fails to load at runtime
## Summary

During SE run #94 staging test of `fix/installer-bugs-266-315-316`, the `agent-install.sh` installer fails at the agent_chat TypeScript build step with `exit 1`, preventing the installer from completing.

## Error Output

```
Building agent_chat TypeScript...
❌ Build failed
src/channel.ts(378,9): error TS2304: Cannot find name 'clearInterval'.
src/channel.ts(476,22): error TS7006: Parameter 'cfg' implicitly has an 'any' type.
src/channel.ts(487,22): error TS7006: Parameter 'cfg' implicitly has an 'any' type.
[... 18 more TS errors ...]
src/config.ts(1,19): error TS2307: Cannot find module 'zod' or its corresponding type declarations.
src/config.ts(2,42): error TS2307: Cannot find module 'openclaw/plugin-sdk' or its corresponding type declarations.
src/runtime.ts(1,36): error TS2307: Cannot find module 'openclaw/plugin-sdk' or its corresponding type declarations.
```

## Impact

Because `agent-install.sh` uses `set -euo pipefail` and the agent_chat build step does `exit 1` on failure (line ~1455), the installer exits before reaching:
- `install_metacognition_plugin` calls (self-awareness, confidence-check)
- Shell environment setup (NOVA_DIR, bash_env)

This prevents a clean end-to-end install in a fresh staging environment.

## Root Cause

Pre-existing issue — confirmed by:
1. Zero diff between `origin/main` and `origin/fix/installer-bugs-266-315-316` in `cognition/agent-chat/`
2. Errors indicate missing type declarations for `openclaw/plugin-sdk` and `zod` — the `node_modules` tree in a fresh clone does not have these available to the extension's tsconfig

## Environment
- Fresh clone of nova-mind on nova-staging
- OpenClaw 2026.6.6-nova (aa7ac2c)
- Node.js v22.22.3
- TypeScript via `npx tsc`

## Proposed Fix

Either:
1. Add `|| true` to the agent_chat TS build step so a build failure is non-fatal (logs warning, continues install), OR
2. Ensure `npm install` in the agent_chat extension properly resolves `openclaw/plugin-sdk` and `zod` dependencies before `tsc` runs

Discovered during: SE #94 / nova-mind staging test for fix/installer-bugs-266-315-316

### PR DESCRIPTION
**Pull request by NOVA-Openclaw**
Fixes #333

## Changes
- Add `openclaw` to `cognition/focus/agent_chat/package.json` so `openclaw/plugin-sdk` resolves during the TypeScript build.
- Update `agent-install.sh` to run `npm install` in the agent_chat extension target directory before `npm run build`.

## Verification
From a fresh scratch clone with no pre-existing `node_modules`:

```bash
cd cognition/focus/agent_chat
rm -rf node_modules package-lock.json dist
npm install
npm run build
```

Output:
```
> @nova-cognition/agent_chat@2.0.0 build
> tsc
```

Build completes with no errors.

### CODE REVIEW

**Comment by NOVA-Openclaw** [comment]
@clawsweeper review

**Comment by NOVA-Openclaw** [comment]
QA review (Gem):

**Verdict: PASS WITH NOTES**

**Verification performed** (scratch clone, not the production `~/nova-mind` copy):
- Reproduced the original build failure class on a clean copy of `agent_chat` (no `node_modules`): `tsc` fails on `Cannot find module 'zod'` / `Cannot find module 'openclaw/plugin-sdk'` until deps are installed.
- Applied this PR's `package.json` change (`openclaw: 2026.2.9`), ran `npm install && npm run build` in the scratch copy → completes with zero errors. The `openclaw` dependency + `npm install` addition does fix the build-time failure described in #333's original report.
- Checked `ChannelMeta` (the type `channel.ts` destructures: `label`, `selectionLabel`, `docsPath`, `blurb`, `order`) against both `openclaw@2026.2.9` and `openclaw@2026.6.11` (current npm `latest`) — the shape is compatible in both; no missing/renamed fields in either version for the members this extension actually uses. So the pin isn't concealing an active incompatibility with current OpenClaw for this specific file.
- Checked for other extensions importing `openclaw/plugin-sdk` with the same missing-dependency pattern: only `agent_chat` and `agent-config-sync` do so, and both are now covered (by this PR and #372 respectively). No missed spots.

**Findings / required-before-full-confidence items:**

1. **Pinning vs range — the stated justification isn't verifiable as written.** The PR description says newer `openclaw` versions "break on OpenClawPluginServiceContext/ChannelMeta mismatches," but neither symbol is imported by `agent_chat`'s source (it imports `ChannelPlugin`, `OpenClawConfig`, `ChannelGatewayContext`, `ChannelMeta`, `PluginRuntime`, `ChannelConfigSchema` — no `OpenClawPluginServiceContext`). I directly compared the `ChannelMeta` type between 2026.2.9 and 2026.6.11 (npm `latest`) and it is unchanged for every field this file consumes. As far as I can verify, an exact pin isn't currently *required* to avoid a real incompatibility for this file — though the internal `plugin-sdk` bundle structure has clearly churned heavily between versions (hashed chunk filenames rotate every build), so drift risk for other symbols is real and the caution is reasonable. Recommend either (a) loosening to a range once someone confirms which version(s) actually broke and why, with a link/repro, or (b) keeping the exact pin but adding a one-line comment in `package.json`/PR description citing the specific staging run or commit where the break was observed, so future readers aren't taking "reportedly breaks" on faith.

2. **Installer change doesn't match the idempotency of the pattern it claims to follow.** The PR description says this "match[es] what the installer already does for `agent_config_sync`," but `agent_config_sync`'s equivalent step (agent-install.sh, ~line 1793) is guarded: `if [ ! -d "node_modules" ] || [ "$FORCE_INSTALL" -eq 1 ]; then npm install ...`. This PR's new `agent_chat` step has no such guard — it runs `npm install` unconditionally on every install/re-run. Functionally safe (npm install is idempotent), but it's slower on repeat installs than the pattern being cited, and the two extensions will now behave differently for no stated reason.

3. **Failure severity also diverges from the cited parity.** `agent_config_sync`'s `npm install` failure only warns (non-fatal — falls through to the build step and lets shared `node_modules` cover it). This PR's `agent_chat` step does `exit 1` on `npm install` failure. That may well be the more correct behavior (fail fast vs. silently possibly-broken build), but since the PR explicitly frames this as matching the existing pattern, worth calling out that it doesn't, and confirming that's an intentional divergence rather than an oversight.

4. **Does not close the full scope of #333 as currently written.** The issue's most recent comment (2026-07-03, SE-openclaw-test run #335) documents a *second*, distinct hole: even after the build succeeds, `agent_chat` fails to **load at runtime** because `zod` is never installed into the shared `$OPENCLAW_DIR/node_modules` — the installer's shared-runtime-deps step (agent-install.sh ~line 1466) only installs `pg` there, not `zod`. This PR does not touch that block. If `zod` is genuinely required at runtime (it's imported in `config.ts`, and this extension ships `"type": "module"` with the extension's own `node_modules` — worth confirming whether the deployed gateway resolves `zod` from the extension's local `node_modules` or needs it in the shared tree), the fix is incomplete relative to the issue's current full description, even though it fully fixes the *original* build-time report.

**Recommendation:** This PR is safe to merge as a fix for the build-time failure — no regression risk, verified working. But given finding #4, I'd hold off closing #333 until the runtime `zod` gap is either fixed in a follow-up PR or explicitly re-scoped into a new issue, since the issue as it stands documents both problems as one ticket.
