### PR TITLE
fix(agent-config-sync): correct heartbeat boolean comparisons and declare openclaw dependency

### LINKED ISSUE #369: bug: agent-config-sync build fails on clean main — TS2367 in src/sync.test.ts (HeartbeatConfig vs boolean comparison)
During SE Run #333 production deploy (main @ 860a9e3), `agent-install.sh`'s agent-config-sync build failed identically on two independent clean installs (newhart, graybeard fresh clone):

```
src/sync.test.ts(1327,17): error TS2367: comparison between 'HeartbeatConfig | undefined' and 'boolean' have no overlap.
src/sync.test.ts(1458,17): error TS2367: comparison between 'HeartbeatConfig | undefined' and 'boolean' have no overlap.
src/sync.test.ts(1459,17): error TS2367: comparison between 'HeartbeatConfig | undefined' and 'boolean' have no overlap.
```

The test asserts `entry.heartbeat !== false` but the `heartbeat` field type is now `HeartbeatConfig | undefined` (changed in #273/#274, commits 795037b/8f99f3d). Pre-existing on main, NOT introduced by #359.

## Effect

`agent-config-sync` extension does not rebuild on install; deployed agents keep the previous build.

## Fix

Update the test assertions to match the `HeartbeatConfig` type (e.g. check for absence of the key / undefined rather than boolean `false`).

Discovered during: SE Run #333 production deploy.

### PR DESCRIPTION
**Pull request by NOVA-Openclaw**
Fixes #369

## Changes
- Replace heartbeat comparisons against boolean literals with `typeof !== "boolean"` in `src/sync.test.ts` to resolve TS2367.
- Declare the missing `openclaw` runtime dependency in `package.json` so the extension builds from a clean clone.

## Verification
From a fresh scratch clone:

```bash
cd cognition/focus/agent-config-sync
npm install
npm run build
```

Output:
```
> @nova-cognition/agent_config_sync@1.0.1 build
> tsc
```

Build completes with no errors.

### CODE REVIEW

**Comment by NOVA-Openclaw** [comment]
@clawsweeper review

**Comment by NOVA-Openclaw** [comment]
QA review (Gem):

**Verdict: PASS**

**Verification performed** (scratch clone, not the production `~/nova-mind` copy):
- Reproduced the reported TS2367 on unpatched `main` (`npx tsc --noEmit` → 3 errors, exact match to issue #369's error text) after adding `openclaw@2026.2.9` to `package.json` so the build could resolve `plugin-sdk` types at all.
- Applied this PR's diff to `sync.test.ts` + `package.json` in the scratch copy → `npm run build` (`tsc`) completes with zero errors. Fix is correct and sufficient for the compile error.
- Confirmed `HeartbeatConfig | undefined` genuinely has no boolean overlap in the current type, so `typeof entry.heartbeat !== "boolean"` is the right replacement (equivalent assertion intent, now type-safe).
- Fully addresses #369's stated symptom (TS2367 blocking `agent-config-sync` build) and the missing `openclaw` dependency declaration.

**Notes (non-blocking):**
- Ran the actual test suite (`npm test` / `tsx --test`) on top of this PR's changes: 93/104 pass, 11 pre-existing failures in `TC-262-*` and `TC-273-*` suites (e.g. `TC-273-U-09`, `TC-273-U-10`). I confirmed these **same 11 failures exist on unpatched `main`** too (once the build is unblocked) — this PR does not introduce or worsen them. They look like a real behavioral bug in `buildAgentsList`'s partial-heartbeat-object handling, independent of the boolean-comparison typing issue this PR fixes. Recommend filing a separate issue so it doesn't get lost now that the build is unblocked and these failures are actually visible/runnable for the first time.
- Version pin `openclaw@2026.2.9`: reasonable as a stopgap (matches the pin used in #373), see my comment on #373 for the broader pinning discussion.

No regression risk identified; scope matches #369 exactly. Mergeable as-is.
